apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalogdetail
  namespace: workshop
spec:
  hosts:
  - catalogdetail
  http:
  - match:
    - headers:
        x-tenant:
          exact: test-user
    route:
    - destination:
        host: catalogdetail
        port:
          number: 80
        subset: v2
  - route:
    - destination:
        host: catalogdetail
        port:
          number: 80
        subset: v1