apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: {{ .Release.Namespace }}
  labels:
    app: productcatalog
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 5000
  selector:
    app: productcatalog