apiVersion: v1
kind: Service
metadata:
  #annotations:
  # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
  #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: productui
  namespace: {{ .Release.Namespace }}
  labels:
    app: productui
spec:
  ports:
    - name: "http"
      port: 9000
      targetPort: 9000
  selector:
    app: productui